### ISSUE TITLE
Routing issue when ‘string’ and ‘boolean’ variables are used in a split predicate

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#554]
[xor_boolean.yawl.gz](https://github.com/yawlfoundation/yawl/files/290358/xor_boolean.yawl.gz)
[xor_string.yawl.gz](https://github.com/yawlfoundation/yawl/files/290359/xor_string.yawl.gz)
[xor_int.yawl.gz](https://github.com/yawlfoundation/yawl/files/290360/xor_int.yawl.gz)
[xor_integer.yawl.gz](https://github.com/yawlfoundation/yawl/files/290361/xor_integer.yawl.gz)

The Editor allows specifying a variable value in a split predicate definition without using quotes (e.g., on pictures below). However, if the variable type is ‘string’ or ‘boolean’ the case will always follow the default path during execution (see the attached specifications ‘xor_boolean.yawl’ and ‘xor_string.yawl’). If quotes are used in predicate definitions, then task ‘B’ can be executed. If the variable type is ‘int’ or ‘integer’ and quotes are not used, task ‘B’ can still be executed (e.g., in the attached specifications ‘xor_int.yawl’ and ‘xor_integer.yawl’). OR-split predicates display the same behaviour.

![image](https://cloud.githubusercontent.com/assets/14101966/15663348/741eac92-273d-11e6-9a01-1b92aff58d48.png)

![image](https://cloud.githubusercontent.com/assets/14101966/15663351/78e06bee-273d-11e6-8dd4-fda864ca4aa9.png)

![image](https://cloud.githubusercontent.com/assets/14101966/15663354/7e9d9ce6-273d-11e6-937e-7a91591f4e9a.png)

![image](https://cloud.githubusercontent.com/assets/14101966/15663359/86bcea12-273d-11e6-894a-9714509541da.png)

**Comment by yawlfoundation** [comment]
All are valid XPath boolean expressions, as explained on page 129 of the YAWL user manual. 

I'll amend the user manual to reference this page from the editor chapter's discussion of split predicates.

A valid XPath expression to any ‘node’ is treated as true, even if the value of the node is a string or integer, for example (i.e. testing the node’s existence rather than its value).
• A single boolean value is treated as that value (i.e. ‘true()’ or ‘false()’).
• If it is a single string, then if it is zero length it is treated as false, otherwise it is treated as true.
For example, ‘abc’ and ‘false’ will evaluate to true.
• If it is a single numeric value, then if the value is NaN or zero it is treated as false; otherwise it is treated as true. For example, -37 and 432 will evaluate to true.
