### ISSUE TITLE
Cancellation regions: soundness and OR-join issues

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#558]
[cancellation.yawl.gz](https://github.com/yawlfoundation/yawl/files/299768/cancellation.yawl.gz)

**#1**
Analysis results for the attached specification (cancellation.yawl) indicate that the net does not have an option to complete:
![image](https://cloud.githubusercontent.com/assets/14101966/15812470/d0ec8e8e-2bf8-11e6-9e2d-8072f0b660a5.png)

**#2**
During execution of the process, after tasks ‘b’ and ‘c’ are completed (and task ‘a’ is not completed yet) task ‘end’ becomes enabled.

**Comment by yawlfoundation** [comment]
This not a bug but the intended semantics of an OR-join.

In this net, it is never possible to mark all three input places of the OR-join in a marking, hence it will fire. This is because when A completes it will remove the tokens B-end and C-end. 

If you need the OR-join to wait for A to complete after B and C, remove the flows B-end and C-end from A's cancellation set.

With just one cancellation set, the net is not sound as when Task A is completed, the OR-join will fire again. We will need another cancellation net (to remove tokens associated with A) if we want to preserve the soundness property of this net.

[thanks to Moe for verifying this]
