### ISSUE TITLE
Sequence data types and MI tasks

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#576]
[complexDataMItask.yawl.gz](https://github.com/yawlfoundation/yawl/files/315517/complexDataMItask.yawl.gz)

In the attached specification (‘complexDataMItask.yawl’) a complex data type (‘Hoppers’) is defined that comprises a sequence of elements (min=0; max=3). A variable of this type is marked as MI for MI task ‘b’; two instances of ‘b’ are created at run-time. During execution of the process, if fewer than 2 elements are defined for the variable of type ‘Hoppers’, MI task ‘b’ can’t be started (see errors on the figures below). If possible, it would be helpful to warn users earlier about the required number of elements for the MI task variable.

![image](https://cloud.githubusercontent.com/assets/14101966/16069887/2a8b93e0-3315-11e6-821e-3a9219b9ade1.png)

![image](https://cloud.githubusercontent.com/assets/14101966/16069895/32ea3384-3315-11e6-921f-01e922901809.png)

**Comment by a-pika** [comment]
Another possible improvement - to display a warning in the Editor if an MI task has no an input variable marked as MI.

**Comment by a-pika** [comment]
Another related issue: when the number of instances created at run-time is higher than the maximum number of elements allowed in the complex data type definition (it is possible when dynamic instance creation is allowed), after MI task is completed a user gets the error:
![error](https://cloud.githubusercontent.com/assets/14101966/16181971/8de36a08-36e4-11e6-83b4-8a26c13b3483.png)

**Comment by yawlfoundation** [comment]
1: Unfortunately, there's no way to predict whether task 'a' will complete with the minimum required data instances before 'b' starts. Also, when 'a' is executing, there is no way of telling whether the data it outputs will be required for a subsequent MI task. The onus is really on the (human) designer to ensure the number of data instances supplied as input at runtime will meet the minimum specified at design time.

2: Unfortunately, an MI task without an MI variable has to be allowable, otherwise there are problems running validation and analysis routines.

3: see (2) - an MI task's min, max, threshold attributes must be able to be set independently from its data variable (and the variable can be changed at any time during design), so again the onus must be on the designer to create the correct & matching maxOccurs in the data type to the max set for the MI attributes. Note that at runtime a user will be block from creating more instances than that set in the max attribute.
