### ISSUE TITLE
Output binding modified without warning in the Editor

### ISSUE THREAD

**Issue by a-pika** [yawlfoundation/yawl#586]
[outputBinding.yawl.gz](https://github.com/yawlfoundation/yawl/files/336146/outputBinding.yawl.gz)

**Steps**: in the attached specification (‘outputBinding.yawl’) open ‘Data variables’ for task ‘a’ -> create another task variable with scope ‘Output’ (e.g. ‘var2’) and bind it with net variable ‘var’ 

**Result**: Output binding for task variable ‘var’ is modified (without warning):

![image](https://cloud.githubusercontent.com/assets/14101966/16401657/afb835be-3d29-11e6-9855-e6ea2085931f.png)

**Comment by yawlfoundation** [comment]
This is because the output binding belongs to the task, not the variable. In the output bindings dialog in the example, we are looking at the binding that outputs to net variable 'var'.

Nevertheless, there is a warning dialog when an output binding is about to overwrite an existing one, with 'yes, no, cancel' options.
