### ISSUE TITLE
AbstractCodelet should load inParams and outParams in the constructor

### ISSUE THREAD

**Issue by Marco-Sulla** [yawlfoundation/yawl#624]
The population of these two parameters are demanded to the `execute()` method, since `YAWL` passes these parameters to it. I think that `YAWL` should pass these parameters to the constructor instead, and `execute()` will be a method with only the `inData` parameter. IMHO it's much more standard this way.

Furthermore, I think it's more simple if `inParams` and `outParams` will be a `Map<String, YParameter>`, so you have no to cycle over the parameters every time one needs to get a parameter by its name.

**Comment by adamsmj** [comment]
A codelet is loaded by the class loader exactly once. Since each task will have different parameters, these cannot be passed to the constructor, but rather must be passed to the execute method.

Task parameters and stored as lists throughout the system. You are free to change the lists to maps in your codelet implementation as you wish.
